#!/usr/bin/ansible-playbook
---
- hosts: localhost
  roles:
    - role: role-aliases
      become: true
  tasks:
    - name: configure terminal colors
      include_tasks: tasks/configureColors.yml

    - name: install terraform
      include_tasks: tasks/installTerraform.yml

    - name: install node
      include_tasks: tasks/installNode.yml

    - name: install go
      include_tasks: tasks/installGo.yml

    - name: install docker
      include_tasks: tasks/installDocker.yml
