#!/usr/bin/ansible-playbook
---
- hosts: localhost
  tasks:
    - name: configure common aliases
      lineinfile:
        path: ~/.bash_aliases
        line: "{{ item }}"
        state: present
        create: true
      loop:
        - alias clera="clear"
        - alias gs="git status"
        - alias gl="git branch -l"

    - name: configure terminal colors
      include_tasks: tasks/configureColors.yml

    - name: install terraform
      include_tasks: tasks/installTerraform.yml

    - name: install node
      include_tasks: tasks/installNode.yml

    - name: install go
      include_tasks: tasks/installGo.yml

    - name: install docker
      include_tasks: tasks/installDocker.yml
