---
- name: install required packages
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - python3-pip
    state: present

- name: add docker gpg key
  become: true
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add docker repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/debian buster stable
    state: present

- name: install docker packages
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: true

- name: install docker compose
  become: true
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/sbin/docker-compose
    mode: 0744

- name: ensure docker group exists
  become: true
  group:
    name: docker
    state: present

- name: ensure users are members of docker group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
