---
- name: install required packages
  apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
    state: latest
  loop:
    - gnupg
    - software-properties-common
    - curl

- name: add terraform gpg key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg

- name: add terraform apt repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com bullseye main
    update_cache: true
    state: present

- name: install terraform
  apt:
    name: terraform
