---
- name: install nvm
  shell: |
    mkdir -p {{ ansible_env.HOME }}/.nvm
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | NVM_DIR={{ ansible_env.HOME }}/.nvm bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: install latest version of node
  shell: source ~/.nvm/nvm.sh && nvm install --lts
  args:
    executable: /bin/bash
